In [1]:
#Broadcasting is a powerful feature of NumPy that allows you to perform
# operations on arrays of different shapes without creating copies

import numpy as np


In [4]:
arr=np.array([1,2,3,4,5,6])

In [5]:
arr+10

array([11, 12, 13, 14, 15, 16])

In [6]:
 # Broadcasting with Arrays of Different Shapes

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [7]:
arr1+arr2

array([5, 7, 9])

In [10]:
# Example: Broadcasting a 2D Array and a 1D Array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3,4])
result = arr1 + arr2 

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

In [9]:
result

array([[2, 4, 6],
       [5, 7, 9]])

In [14]:
# one more example (3,1)  
arr= np.array([10,20,30])
arr2= np.array([[10],[20],[30]])
arr+arr2

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60]])

In [15]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
[15, 25, 35],
[20, 30, 40],
[25, 35, 45],
[30, 40, 50]])
# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)
# Normalizing the data using broadcasting
normalized_data = (data - mean) / std
print(normalized_data)


[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
