In [1]:
import numpy as np 


In [44]:
array= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [6]:
flat=array.flatten()

In [7]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
flat[0]

1

In [9]:
flat[:3] # same as flat[0:3]

array([1, 2, 3])

In [10]:
## evaery second elemmt 
flat[::2]

array([ 1,  3,  5,  7,  9, 11])

In [17]:
## slicing in numpy 
#note: slicing in numpy returns a view, not a copy
# which is not in the case of list 
print(flat)
b=flat[4:6]

len(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


2

In [18]:
b[0]=78

In [19]:
flat

array([ 1,  2,  3,  4, 78,  6,  7,  8,  9, 10, 11, 12])

In [21]:
## we can use a copy instead 
c=flat[4:6].copy()

In [23]:
c[0]=90

In [24]:
flat

array([ 1,  2,  3,  4, 78,  6,  7,  8,  9, 10, 11, 12])

In [27]:
## Exercises 
# create a 3*3 array with random in
arr=np.random.rand(3,4)

In [28]:
arr

array([[0.83608709, 0.94666469, 0.16869811, 0.92866187],
       [0.43125118, 0.23167406, 0.50386918, 0.84623417],
       [0.20109016, 0.60713708, 0.31977166, 0.73020375]])

In [29]:
arr.shape


(3, 4)

In [37]:
arr1=np.array([1.1, 2.2, 3.6])

In [31]:
arr1

array([1.1, 2.2, 3.3])

In [38]:
flot_array= arr1.astype(int)
flot_array

array([1, 2, 3])

In [40]:
# fancy indexing 
nums=np.array([1, 2, 3, 4, 5, 6])

In [45]:
nums[nums%2==0]

array([2, 4, 6])

In [47]:
to_reshape=np.array([1,2,3,4,5,6,7,8,9])
reshaped= to_reshape.reshape((3,3))
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])