In [1]:
import numpy as np


In [2]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [4]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [5]:
arr[0][2]

3

In [6]:
arr[0,1]

2

In [9]:
# slicing for 2-d arrays 
print(arr[:2,1:5])  # rows: 0,1 column : 1 or greater

[[2 3]
 [5 6]]


In [11]:
# indexing in the 3-d arrays 
# first index refers to the depth of the array
# its like a stack of planes 
arr3d = np.array([[[1,2,3],[4,5,6]]
                   ,[[2,4,6],[8,10,12]]])
arr3d.shape


(2, 2, 3)

In [13]:
np.sum(arr3d,axis=0)  # sum of the 2-d arrays at diff locs

array([[ 3,  6,  9],
       [12, 15, 18]])

In [15]:
# indexing in 3-d
arr3d[0,1,1
]

5

In [17]:
 print(arr3d[:, 0, :]) # both the depths 

[[1 2 3]
 [2 4 6]]
