In [2]:
import numpy as np
import time

In [4]:

# Python zip 
l1=[1,2,3] 
l2=[4,5,6]
list(zip(l1,l2))

[(1, 4), (2, 5), (3, 6)]

In [14]:
 # initialize big size lists
size=1_000_000_0
list1= list(range(size))
list2= list(range(size))


In [15]:

# for lists
start=time.time()
l3= [x+y for x,y in zip(list1,list2)]
end= time.time()
print(end-start)

1.1623330116271973


In [18]:
# for numpy 
arr1= np.array(list1)
arr2= np.array(list2)
start= time.time()
arr3= arr1+arr2
end= time.time()
print(end-start)
               


0.03121471405029297


In [22]:
# 2-d array 
aray2d= np.array([[1,2,3],[3,4,5]])
print(aray2d)

[[1 2 3]
 [3 4 5]]


In [23]:
type(aray2d)

numpy.ndarray

In [26]:
print(aray2d.shape)


(2, 3)


In [27]:
## memeory efficiency in numpy 
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 4000 bytes


In [32]:
# another example of time 
lst=list(range(10000))
start= time.time()
squared_lst=[x**2 for x in lst]
end = time.time()
print(end-start)


0.0029993057250976562


In [39]:
arr_tmp=np.array(lst)
start1= time.time()
np_squared= arr_tmp**2
end1 = time.time()
print(end1-start1)

0.0


In [38]:
start1= time.time()
np_squared= arr_tmp**2
end1 = time.time()
print(end1-start1)

0.0


In [42]:
# numpy array exercises 
array= np.array(range(10,101))

In [45]:
array

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [46]:
size=1000_000
list= list(range(size))
print(sys.getsizeof(list))

8000056


In [47]:
array= np.array(list)
array.nbytes

4000000